### PR TITLE
Adding Yirang Park to members on SECQUOIA website

### PR DESCRIPTION
**Pull request by parkyr**
Uploaded a picture for profile picture (/assets/members) 
Added information on Yirang Park in the Members

### CODE REVIEW

**Review by bernalde — APPROVED** [review]
Great! We'll merge this once Zedong approves it.

**Comment by ZedongPeng** [comment]
Great job on this! Just one more thing to note: I recommend cropping your picture into a square format for consistency and optimal display. Thanks!

**Review by ZedongPeng — CHANGES_REQUESTED** [review]
Hi @parkyr . Since we just merged the PR from Anurag, there are conflicts that needs to be resolved. You can refer to the following link.
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github

**Comment by parkyr** [comment]
Close request: a new request will be made with a new picture and resolution for the conflict with Anurag's upload.

**Pull request closed without merging**
